few_shots = [
    {'Question': "What is the status of loan application with ID 12345?",
     'SQLQuery': "SELECT loan_status FROM loan_applications WHERE loan_id = 12345",
     'SQLResult': "Result of the SQL query",
     'Answer': "Approved"},
    {'Question': "How many loan applications were approved today?",
     'SQLQuery': "SELECT COUNT(*) FROM loan_applications WHERE loan_status = 'Approved' AND DATE(loan_date) = CURDATE()",
     'SQLResult': "Result of the SQL query",
     'Answer': "12"},
    {'Question': "How many loan applications were denied this month?",
     'SQLQuery': "SELECT COUNT(*) FROM loan_applications WHERE loan_status = 'Denied' AND MONTH(loan_date) = MONTH(CURDATE())",
     'SQLResult': "Result of the SQL query",
     'Answer': "5"},
    {'Question': "What is the average loan amount requested by applicants with a credit history of 1?",
     'SQLQuery': "SELECT AVG(loan_amount) FROM loan_applications WHERE credit_history = 1",
     'SQLResult': "Result of the SQL query",
     'Answer': "$15000"},
    {'Question': "How many loan applications have an applicant income greater than $5000?",
     'SQLQuery': "SELECT COUNT(*) FROM loan_applications WHERE applicant_income > 5000",
     'SQLResult': "Result of the SQL query",
     'Answer': "20"},
    {'Question': "What is the total loan amount for applications in the 'Urban' property area?",
     'SQLQuery': "SELECT SUM(loan_amount) FROM loan_applications WHERE property_area = 'Urban'",
     'SQLResult': "Result of the SQL query",
     'Answer': "$500000"}
]
